on:
  release:
    types:
      - published
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Build
        run: npm install && npm run dist
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: distribution
          path: majordomo.tar.gz
  release: 
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - name: Download a Build Artifact
       uses: actions/download-artifact@v2.0.5
       with:
         name: distribution
         path: majordomo.tar.gz
